apiVersion: v1
kind: Service

metadata:
  name: stockloom-frontend-service
  namespace: stockloom

spec:
  selector:
    app: stockloom-frontend

  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30007

  type: NodePort