apiVersion: v1
kind: Secret

metadata:
  name: stockloom-secrets
  namespace: stockloom

type: Opaque

data:
  POSTGRES_DB: c3RvY2tsb29t
  POSTGRES_USER: c3RvY2tsb29t
  POSTGRES_PASSWORD: c3RvY2tsb29t