apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: stockloom-disallow-privileged
  annotations:
    policies.kyverno.io/title: Disallow Privileged Containers
spec:
  validationFailureAction: Enforce
  rules:
    - name: no-privileged
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: [stockloom]
      validate:
        message: "Privileged containers are not allowed in StockLoom"
        pattern:
          spec:
            containers:
              - =(securityContext):
                  =(privileged): false
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: stockloom-require-resource-limits
spec:
  validationFailureAction: Enforce
  rules:
    - name: require-limits
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: [stockloom]
      validate:
        message: "Resource limits are required"
        pattern:
          spec:
            containers:
              - resources:
                  limits:
                    memory: "?*"
                    cpu: "?*"
