name: StockLoom Lint

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev


jobs:

  backend-lint:
    name: Backend Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
version: "3.8"
services:
  db:
    image: postgres:16
    container_name: stockloom-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    image: stockloom-be
    container_name: stockloom-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./backend/.env
    ports:
      - "8002:8000"

  frontend:
    build: ./frontend
    image: stockloom-fe
    container_name: stockloom-frontend
    restart: always
    depends_on:
      - backend
    environment:
      - API_BASE_URL=http://stockloom-backend:8000/api
    ports:
      - "8081:8081"

volumes:
  pgdata:

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black


      - name: Ruff check backend
        run: |
          ruff check backend/app \
          --ignore E501 \
          --exclude backend/venv,backend/prod


      - name: Black format check
        run: |
          black --check backend/app


  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black


      - name: Ruff check frontend
        run: |
          ruff check frontend \
          --ignore E501 \
          --exclude frontend/venv,frontend/prod


      - name: Black format check frontend
        run: |
          black --check frontend


  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install Bandit
        run: |
          pip install bandit


      - name: Run Bandit
        run: |
          bandit -r backend/app -ll
        continue-on-error: true