name: StockLoom Lint

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev


jobs:

  backend-lint:
    name: Backend Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black


      - name: Ruff check backend
        run: |
          ruff check backend/app \
          --ignore E501 \
          --exclude backend/venv,backend/prod


      - name: Black format check
        run: |
          black --check backend/app


  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"


      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black


      - name: Ruff check frontend
        run: |
          ruff check frontend \
          --ignore E501 \
          --exclude frontend/venv,frontend/prod


      - name: Black format check frontend
        run: |
          black --check frontend


  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install Bandit
        run: |
          pip install bandit


      - name: Run Bandit
        run: |
          bandit -r backend/app -ll
        continue-on-error: true